project_id = "mhhlrcmwtypahmqdpbww"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-paddle-checkout]
    verify_jwt = false
  [functions.geo-detect]
    verify_jwt = false
  [functions.get-paddle-client-token]
    verify_jwt = false
  [functions.paddle-webhook]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.submit-contact]
    verify_jwt = false
  [functions.verify-paddle-prices]
    verify_jwt = false
  [functions.process-email-outbox]
    verify_jwt = false
